name: sews_connect
description: "SEWS Connect - Comprehensive company communication app with messaging, calls, meetings, dashboard, notifications, QR scanning, and task management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # State Management
  provider: ^6.1.2
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # UI Components
  material_design_icons_flutter: ^7.0.7296
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Real-time Communication
  socket_io_client: ^2.0.3+1
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^0.11.6+hotfix.1
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Real-time Communication
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_database: ^10.4.9
  cloud_firestore: ^4.15.8
  
  # Push Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  
  # Camera & QR/Barcode
  camera: ^0.10.5+7
  mobile_scanner: ^3.5.6
  
  # Permissions
  permission_handler: ^11.1.0
  device_info_plus: ^10.1.0
  
  # File Handling
  file_picker: ^6.1.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  csv: ^5.0.2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
